FROM node:22-slim AS build
WORKDIR /w
COPY web/package*.json ./
RUN npm ci
COPY web/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /w/dist /usr/share/nginx/html
COPY deploy/v2/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
